### ISSUE TITLE
KeyError: 'noise_std' 

### ISSUE THREAD

**Issue by letian-jiang** [RITCHIEHuang/MAGAIL#1]
Hi, it seems like that the hyperparameter `noise_std` is missing in config.yml. 

Could you add it?  

Thanks!

**Comment by RITCHIEHuang** [comment]
@happylotte Thanks for reminding me ! 
The `noise_std` parameter is a trick like `instance noise` on GANs, it may be helpful to train the algorithm by adding that noise to input of `Discriminator`. I will choose not to add noise here , It' been fixed now. 
Thanks!
