### ISSUE TITLE
Why do we need the variable "masks" in the process of GAE?

### ISSUE THREAD

**Issue by yangzq-hub** [RITCHIEHuang/MAGAIL#2]
It seems that "masks" is used to show whether the reward and the value are at the end of a trajectory. But why do we need it when doing GAE? The code is at the 32nd and 33rd line of GAE.py.
deltas[i, ...] = rewards[i, ...] + gamma * prev_value * masks[i, ...] - values[i, ...]
advantages[i, ...] = deltas[i, ...] + gamma * tau * prev_advantage * masks[i, ...]

**Comment by RITCHIEHuang** [comment]
It's actually the calculation of GAE($\lambda$)：
![image](https://user-images.githubusercontent.com/16410627/159113420-b530ccf8-7e51-4d4c-bf69-1de24a362e6a.png)
In our case, the calculation is applied to batched trajectories so you can say it's not necessary to add masks[I, ...] in the 33rd line.
But you can understand in a more general case that you calculate the GAE with an input of two consecutive trajectories:
$$(s_0, a_0, r_0, \cdots, s_T, a_T, s_{T+1}, a_{T+1}, r_{T+1}, \cdots, s_{T+T1}, a_{T+T1}, r_{T+T1})$$. 
where T is the end of the first trajectory, and T1 is the length of the second trajectory.

Actually, the GAE estimation of trajectory 1 can't be involved with trajectory 2, you will need to add extra masks[i,...] to identify the end of each trajectory.

**Comment by yangzq-hub** [comment]
In this way, the "masks" should be 0 at the end of a trajectory, and be 1 at other places. However, in the 69th line of JointPolicy.py, the mask is set to be 1 at the end of a trajectory and 0 at other places. Is this a mistake or I still take something wrong? Thank you.

**Comment by RITCHIEHuang** [comment]
You are right, the mask should be corrected.
