### ISSUE TITLE
专家轨迹获取

### ISSUE THREAD

**Issue by yuanyaaa** [RITCHIEHuang/MAGAIL#3]
您好！我想请问一下，在MAGAIL中，您是怎么获取专家轨迹的呢？

**Comment by RITCHIEHuang** [comment]
MAGAIL inherited the imitation learning framework, it assumes that you already have access to expert data. In our case, it is obtained from the official project <a href="https://github.com/eyounx/VirtualTaobao/tree/master/virtualTB/SupervisedLearning"></a>

**Comment by yuanyaaa** [comment]
> 
“Obtain data from the official project”, can I understand that there is no code realized to obtain expert tracks in the project？

Another question is whether the code implements the decentralized discriminator method?

Thank you for your reply
